# Generated by Django 2.2.5 on 2019-09-02 11:44
from datetime import date

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('phone_no', models.IntegerField(default='', max_length=255)),
                ('email', models.EmailField(default='', max_length=255)),
                ('issue_type',
                 models.CharField(max_length=3, choices=[('1', 'Technical'), ('2', 'Billing'), ('3', 'Service')])),
                ('status', models.CharField(max_length=2, choices=[('1', 'Open'), ('2', 'Closed')])),
                ('description', models.TextField(default='', max_length=255)),
                ('creation_date', models.DateField(default=date.today)),
                ('closed_date', models.DateField(blank=True, editable=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(primary_key=True)),
                ('ticket_id', models.ForeignKey('Ticket', on_delete=models.CASCADE)),
                ('description', models.TextField(default='')),
                ('created_at', models.DateField(default=date.today))
            ],
        ),
    ]