# Generated by Django 2.2.5 on 2019-09-02 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('phone_no', models.IntegerField(default='', max_length=255)),
                ('email', models.EmailField(default='', max_length=255)),
                ('issue_type', models.CharField(default='', max_length=255)),
                ('status', models.CharField(default='', max_length=255)),
                ('description', models.TextField(default='', max_length=255))
            ],
        ),
    ]