# Generated by Django 2.2.6 on 2019-10-24 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='phone_no',
            field=models.IntegerField(default=''),
        ),
    ]
