# Generated by Django 2.2.5 on 2019-10-26 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketApp', '0004_auto_20191026_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='created_at',
            field=models.DateField(verbose_name='today'),
        ),
    ]
